### ISSUE TITLE
Error Builing App

### ISSUE THREAD

**Issue by boardmain** [IcaliaLabs/LoginKit#11]
hi after i install LoginKit from cocoapod

if i try the run the app i have this error in build phase

"FBSDKLoginKit" Incopatible block pointer types 'void(^)(BOOL) to parameter tof type 'void.....
line 505 FBSDKLoginManager.m

same error line 549 and 551

**Comment by boardmain** [comment]
the problem is with the last FacebookCore update with version 4.25.0

**Comment by likeaj6** [comment]
also having this issue

**Comment by danlozano** [comment]
Yeah, it's a Facebook SDK update.

Will update ASAP and get this fixed.

Considering switching to having a fixed Facebook SDK version to prevent this problem, and just update once in a while.

**Comment by danlozano** [comment]
This is strange...

I finally got the time to look into this.

Went into the sample project and another personal project I have that uses LoginKit. Updated LoginKit via cocoapods (so the Facebook SDK's would update to version 26), everything good.

Now I run the app, hoping it's going to crash because of the Facebook update, so I can go in and fix whatever changed.

But it worked just fine! What am I missing? When does this error come up? Any clues as to what changed?

**Comment by danlozano** [comment]
Nevermind!

I think the issue is that LoginKit was using the hard-coded-version `FBSDKLoginKit` .18 , but internally that was using a newer version of FBSDKCoreKit, and that was causing the issue I suppose.

Changed LoginKit to use the newest version of FBSDKLoginKit and it seems to be working now!

:)
