### ISSUE TITLE
How to get out of loop Coordinator calling start()

### ISSUE THREAD

**Issue by ghost** [IcaliaLabs/LoginKit#18]
I'm unclear about when I am supposed to be calling .finish(). The logInCoordinator.start() call is in the viewWillAppear of my app's rootViewController like the example shows and after successful LogIn and calling Finish it just goes right back to presenting another LogIn screen. Can someone please help, what am I missing?

**Comment by danlozano** [comment]
Hi!

Calling finish just dismisses the ViewController's. That's not the problem.

The problem is actually in the example code, it can be confusing so I'm going to fix it now.

Any code you add in your viewDidAppear will be called multiple times, every time the screen appears. So when you dismiss the login process, your root view controller appears again and then you are calling loginCoordinator.start() again.

Ideally your login/signup process would be called from a button press or some other action, not in viewDidAppear. But, if it needs to be in viewDidAppear just add a flag `hasShownLogin = false` to make sure you only show the login process once.

Will send an update later today/tomorrow with new features and this issue "fixed" in the example project.
