### ISSUE TITLE
Facebook Login fails with 304 when change FB account on device

### ISSUE THREAD

**Issue by spinach** [IcaliaLabs/LoginKit#19]
If I change my FB account on my device, the sign-in with Facebook will always fail with 304. The solution is probably [this](https://stackoverflow.com/questions/29408299/ios-facebook-sdk-4-0-login-error-code-304).

**Comment by danlozano** [comment]
Hmm ok!

Will look into this later tonight. Thanks.

**Comment by spinach** [comment]
Thanks a lot for the quick response!

Also, is there any way we can donate for your nice work? thanks for everything you're sharing!

**Comment by spinach** [comment]
Hey! Just wondering if you got the chance to take a look at the above? 🙂

**Comment by danlozano** [comment]
Sorry!! @spinach 

I've been really busy with work that I have not had any time to look into this.

Just set a reminder for TODAY after work, I will look at this and all other issues and PR's and upload a new version.

Thanks for your patience :)

**Comment by danlozano** [comment]
This is probably an issue with older versions of iOS because newer versions of iOS (I think iOS 10+) don't have Twitter/Facebook system accounts anymore.

Anyways I'll implement the quick fix just in case. Will have a new version out with this any many other new features/fixes later today/tomorrow.

Thanks for your patience. :)

**Comment by danlozano** [comment]
Will close for now. If you still have the issue after this new release please open issue again and we'll dig into it a little more :)
