### ISSUE TITLE
Can't override default configuration

### ISSUE THREAD

**Issue by dcortright** [IcaliaLabs/LoginKit#23]
I can't seem to override the default configurations. My code is set up just like it was before version 1.0 except for the updates needed for version 1.0. 

**i.e** changing _backgroundImage_ to _configuration.backgroundImage_

It seems as though it's initializing with the defaults before it hits my own in ConfigureAppearance()

**Comment by dcortright** [comment]
Follow up: The other pages seem to have my new configuration such as no gradient and the background image. But the initial view controller itself stays at the defaults.

**Comment by dcortright** [comment]
Sorry for posting three in a row but I see now that I need to define my configuration before I even call _loginCoordinator.start(animated: false)_

Any defaults defined after this will not apply to the initialViewController

**Comment by danlozano** [comment]
No worries! haha

Hmm so you're setting up the configuration from outside the LoginCoordinator? You're not subclassing.

Now that you can use the View Controller's separately, I did design it so that you must configure the view controller before calling `super.viewDidLoad()`.

But I'll look into your issue, which is different because it's in the coordinator not the viewcontrollers, and see if it should be designed differently.

Could you share some code? How it did not work and how it does work now?

Thanks!

**Comment by dcortright** [comment]
Ah, I found what my issue was. I was still calling _configureAppearance()_ after _super.start()_

After switching those two around it works as you designed now!

**Comment by danlozano** [comment]
Oh ok. Awesome! Glad it works now!

**Comment by LazyTravis** [comment]
omg, I meant the same issue. It took me an hour to update the old code. 
Could anybody add more suggestion for the other guys?
